### ISSUE TITLE
g_langs folder

### ISSUE THREAD

**Issue by wincmd64** [turkaysoft/glow#13]
Glow_x64.exe must be able to be run without "g_langs" folder - English lang must be build-in.
So user can operate only with one .exe-file.

**Comment by turkaysoft** [comment]
Hello,

Thank you for your suggestion.
The reason why English and other languages are in the g_langs folder is for those who want to provide translation support and to fix translation errors.

It is programmed this way on purpose.
Thank you for your understanding.
