### ISSUE TITLE
Position of percentage (%) character is wrong

### ISSUE THREAD

**Issue by Villantiqua** [turkaysoft/glow#18]
Hi,
Impressive software! One remark: I noticed that in several places the percentage character (%) is placed before the number. This should be placed behind the number.

**Comment by turkaysoft** [comment]
> Hi, Impressive software! One remark: I noticed that in several places the percentage character (%) is placed before the number. This should be placed behind the number.

Hello,

First of all, thank you for your valuable comment.
I will examine the relevant parts.

You can be sure that I will make a correction in the next patch.
Best regards.

Identified locations:

- Battery percentage section, RAM usage information

**Comment by turkaysoft** [comment]
This issue has been resolved with version v24.09.

**Comment by Villantiqua** [comment]
👍Sent from my iPadOn 5 Jun 2024, at 21:25, Eray ***@***.***> wrote:﻿
This issue has been resolved with version v24.09.
