### ISSUE TITLE
Glow 24.09 some parts look passive.

### ISSUE THREAD

**Issue by OpenSoftware-World** [turkaysoft/glow#23]
![Ekran görüntüsü 2024-06-06 143255](https://github.com/roines45/glow/assets/143949134/ceea1388-acf6-4a53-8a92-cbe0256083ce)

Hello, I installed the new Glow 24.09 version yesterday, but as I marked in the screenshot, some parts seem passive and cannot be accessed. Is this a problem caused by the 24.09 version or are the parts temporarily closed for an operation? @roines45

**Comment by turkaysoft** [comment]
Hello,

In the Installed Drivers and Services section there are some cases that prevent installation. I noticed them later.

Rest assured it will be fixed with Glow 24.10 release on June 14th.

Best regards.

**Comment by OpenSoftware-World** [comment]
> Hello,
> 
> In the Installed Drivers and Services section there are some cases that prevent installation. I noticed them later.
> 
> Rest assured it will be fixed with Glow 24.10 release on June 14th.
> 
> Best regards.

Thank you for your interest, I also really like the Glow software, I think it is an excellent software.
