### ISSUE TITLE
Computer name truncated to 15 characters

### ISSUE THREAD

**Issue by JonnyTech** [turkaysoft/glow#25]
My computer name has 16 characters. The glow report only shows the first 15 characters. Even when trying to export, the filename only has the 15 characters from the report. Tested on v24.08 and v24.08 x64 versions - system language is English.

**Comment by turkaysoft** [comment]
Hello,

Can you share a screenshot?

**Comment by JonnyTech** [comment]
Certainly, but it will have to wait until I am back at work after the weekend. Thank you for your prompt reply.

**Comment by JonnyTech** [comment]
I was called into work today...

![image](https://github.com/roines45/glow/assets/3584732/63aea51e-2cc1-4010-9e12-0782d4b6862c)

**Comment by turkaysoft** [comment]
Hello,

This is because your computer name was changed afterwards.

Your first computer name ends with 0, then it was changed to 01.
In this context, it should be done according to where the change took place.

The part I used may not contain the change.
I will investigate.

Thank you.

**Comment by turkaysoft** [comment]
I took an action to correct the problem.
It will be fixed with version v24.10.

**Comment by JonnyTech** [comment]
I have a script that changes the name but that was done weeks ago and it has been rebooted many times since then.

```wmic computersystem where name="%computername%" call rename name="%newcomputername%"```

Thank you very much for investigating and fixing it.

**Comment by turkaysoft** [comment]
Thanks.

I hope it is fixed, because I set it to pull from the universal computer name data section.
If not, your machine may be doing something different after logon because it is a company computer.

**Comment by JonnyTech** [comment]
Thank you too. There is nothing installed on it that may make it misbehave. It is indeed a company computer but there is no company software installed. It is a clean Windows installation. If you have a test build then I can test it for you.

**Comment by turkaysoft** [comment]
Can you open the relevant test program and take a screenshot?

[CM_TestV1.zip](https://github.com/user-attachments/files/15752795/CM_TestV1.zip)

**Comment by JonnyTech** [comment]
![image](https://github.com/roines45/glow/assets/3584732/5b6754e1-fbf8-4651-8027-26b4343a6a5b)

**Comment by turkaysoft** [comment]
Can you try again?

[GlowTestV2.zip](https://github.com/user-attachments/files/15753052/GlowTestV2.zip)

**Comment by JonnyTech** [comment]
Have left work, shall do so in the morning.

**Comment by JonnyTech** [comment]
![image](https://github.com/roines45/glow/assets/3584732/4d160414-2553-4f4b-9878-693ec2b4330b)
Yay, well done! Thank you.

**Comment by turkaysoft** [comment]
The problem is solved then.
A fix will be released with version v24.10.
