### ISSUE TITLE
A major issue in Glow 24.10.

### ISSUE THREAD

**Issue by OpenSoftware-World** [turkaysoft/glow#31]
In Glow 24.10 version, it says virtualization is enabled in the processor tab even though virtualization is not enabled. @roines45 
![Ekran görüntüsü 2024-06-11 231420](https://github.com/roines45/glow/assets/143949134/6a1a0930-4bb9-41de-bd79-67a6aeb85692)

**Comment by roines45** [comment]
> In Glow 24.10 version, it says virtualization is enabled in the processor tab even though virtualization is not enabled. 
Virtualization returns Active because the Hyper-V feature is active.

**Comment by turkaysoft** [comment]
@LinuxUsersLinuxMint Virtualization returns Active because the Hyper-V feature is active. This is not a problem, this is how it should be.

**Comment by OpenSoftware-World** [comment]
> @LinuxUsersLinuxMint Virtualization returns Active because the Hyper-V feature is active. This is not a problem, this is how it should be.

Well, then how about writing Hyper-V in parentheses? @roines45
