### ISSUE TITLE
Assigned IPv4 Address wrong

### ISSUE THREAD

**Issue by cantoris** [turkaysoft/glow#34]
I'm using v24.10
Network Information - "Assigned IPv4 Address" is always showing the IP that is bound to the vEthernet (Hyper-V Virtual Ethernet Adapter) NIC, irrespective of which adapter I select from the list.

**Comment by turkaysoft** [comment]
Hello,

This is not a problem.
It does not show dynamically according to the selected adapter.

It shows the mode in which the system is currently active.
It is even put in a different container to indicate that it is separate.

**Comment by cantoris** [comment]
Thanks for the quick response.  The IP it is showing is not that of the main network adapter.  The vEthernet adapter whose IP it shows does not even have a default gateway.  I would expect it ought to be showing my LAN adapter which is on a different subnet altogether and is the one that has Internet access...?

**Comment by turkaysoft** [comment]
> Thanks for the quick response. The IP it is showing is not that of the main network adapter. The vEthernet adapter whose IP it shows does not even have a default gateway. I would expect it ought to be showing my LAN adapter which is on a different subnet altogether and is the one that has Internet access...?

I have created a test program for you.
Can you open the program and take a screenshot?

I would also appreciate if you indicate whether it is correct or not.

[Glow_IP_Test.zip](https://github.com/user-attachments/files/15858908/Glow_IP_Test.zip)

**Comment by cantoris** [comment]
Many thanks for looking into this.
![Glow](https://github.com/roines45/glow/assets/5992975/6cce0243-29ba-49b0-87fe-6ec7c04aa951)
The first IPv4 address is the correct address of my LAN adapter, the second IPv4 address is the correct IP of the vEthernet adapter and was the IP address that Glow v24.10 was showing.
The first IPv6 address is the correct Link-Local address of my LAN adapter and the second is the correct Link-Local address of the vEthernet adapter.

**Comment by turkaysoft** [comment]
Thank you for the information. In this context, either we need to show both values or we need to follow another method.

**Comment by turkaysoft** [comment]
Finally, can you try this one in the same way.

[GlowIPTest2.zip](https://github.com/user-attachments/files/15859135/GlowIPTest2.zip)

**Comment by turkaysoft** [comment]
I found the problem and applied a fix.
Now the IPv4 and IPv6 addresses will change dynamically according to the selected adapter.

Thank you for reporting the bug.
You can be sure it will be fixed with Glow v24.11

**Comment by cantoris** [comment]
Thank you very much!
In case you still need it, here's the output from your 2nd file:
![Glow2](https://github.com/roines45/glow/assets/5992975/535288d9-3f0a-41c4-8f18-5aade2fdde7e)

**Comment by turkaysoft** [comment]
> Thank you very much!

Thanks again for the feedback.
I fixed the parsing error as I mentioned.

Glow 24.10 and earlier versions were programmed to come with a single IPv4 and IPv6 address.

This caused it to print the most recent address on the screen when 2 or more addresses were received.

Now it shows according to the selected adapter. In this way, it has become dynamic.
