### ISSUE TITLE
Report export missing in Glow v24.10

### ISSUE THREAD

**Issue by JonnyTech** [turkaysoft/glow#35]
I cannot see the option to export the report in Glow v24.10 - has it been moved or removed?

**Comment by JonnyTech** [comment]
My bad, I had not copied over the new language .ini file so could not see that the export option had moved to the bottom left.

**Comment by turkaysoft** [comment]
Hi,

As I mentioned in the patch notes, the Export feature has been moved to the bottom left.

> The Export Information feature has been redesigned. It is now located at the bottom of the left menu. This provides a more detailed printing service.

![image](https://github.com/roines45/glow/assets/142736624/206534c6-2adf-472e-8aff-edaf25f9f442)
