### ISSUE TITLE
System Family and System SKU not detected on B650E Steel Legend WiFi

### ISSUE THREAD

**Issue by SkybuckFlying** [turkaysoft/glow#38]
<------- MOTHERBOARD INFORMATION ------->

Motherboard Model: B650E Steel Legend WiFi
Motherboard Manufacturer: ASRock
Serial Number: Default string
System Family: Not detected
System SKU: Not detected
Chipset: AuthenticAMD
BIOS Publisher: American Megatrends International, LLC.
BIOS Date: 28.07.2023
BIOS Version: 1.28
SM-BIOS Version: ALASKA - 1
BIOS Mode: UEFI
Last BIOS Time: 51.1 Second
Secure Boot State: Off
TPM Status: Active - Version: 2.0 (2.0, 0, 1.59)
TPM Physical Asset Version: 1.3
TPM Manufacturer: AMD
TPM Manufacturer ID: 1095582720
TPM Manufacturer Version: 6.29.0.6
TPM Full Manufacturer Version: 6.29.0.6
TPM Manufacturer Publisher: AMD
Motherboard Model Version: Default string
Primary Bus Type: PCI
Secondary Bus Type: ISA
BIOS Major-Minor Version: 5.26
SM-BIOS Major-Minor Version: 3.4

**Comment by turkaysoft** [comment]
> <------- MOTHERBOARD INFORMATION ------->
> 
> Motherboard Model: B650E Steel Legend WiFi Motherboard Manufacturer: ASRock Serial Number: Default string System Family: Not detected System SKU: Not detected Chipset: AuthenticAMD BIOS Publisher: American Megatrends International, LLC. BIOS Date: 28.07.2023 BIOS Version: 1.28 SM-BIOS Version: ALASKA - 1 BIOS Mode: UEFI Last BIOS Time: 51.1 Second Secure Boot State: Off TPM Status: Active - Version: 2.0 (2.0, 0, 1.59) TPM Physical Asset Version: 1.3 TPM Manufacturer: AMD TPM Manufacturer ID: 1095582720 TPM Manufacturer Version: 6.29.0.6 TPM Full Manufacturer Version: 6.29.0.6 TPM Manufacturer Publisher: AMD Motherboard Model Version: Default string Primary Bus Type: PCI Secondary Bus Type: ISA BIOS Major-Minor Version: 5.26 SM-BIOS Major-Minor Version: 3.4

Not detected on desktop computers. It is not a bug.
