### ISSUE TITLE
RAM Manufacturer unknown for Corsair Memory Module.

### ISSUE THREAD

**Issue by SkybuckFlying** [turkaysoft/glow#40]
Slot #1 - Unknown / 32 GB

RAM Amount: 32 GB
RAM Type: DDR5
RAM Frequency: 4800 MT/s
RAM Voltage: 1.10 Volt
RAM Form Factor: DIMM
RAM Serial Number: 00000000
RAM Manufacturer: Unknown
RAM Location: P0 CHANNEL A
RAM Width: 64 Bit
RAM Partition Type: DIMM 0
RAM Section Number: CMT64GX5M2B6000Z40

**Comment by turkaysoft** [comment]
> Slot #1 - Unknown / 32 GB
> 
> RAM Amount: 32 GB RAM Type: DDR5 RAM Frequency: 4800 MT/s RAM Voltage: 1.10 Volt RAM Form Factor: DIMM RAM Serial Number: 00000000 RAM Manufacturer: Unknown RAM Location: P0 CHANNEL A RAM Width: 64 Bit RAM Partition Type: DIMM 0 RAM Section Number: CMT64GX5M2B6000Z40

If the manufacturer has left the “manufacturer information” blank, unfortunately there is nothing we can do.
