### ISSUE TITLE
App won't run if non-native language files are deleted

### ISSUE THREAD

**Issue by Mannard** [turkaysoft/glow#9]
I speak English,  why would I need Turkish language files.  
Remove the Turkish lang pack and the app won't run.
Virtually all other apps run without the unnecessary language packs.

**Comment by OpenSoftware-World** [comment]
> I speak English, why would I need Turkish language files. Remove the Turkish lang pack and the app won't run. Virtually all other apps run without the unnecessary language packs.

As a Glow user and fan, I tested what you said and I have the same problem. I use Turkish as my native language, but when I remove English, the application does not work. I hope it gets fixed as soon as possible.

**Comment by turkaysoft** [comment]
@Mannard @LinuxUsersLinuxMint 

Hello,

Thank you for your feedback.
I investigated the problem and identified the issue.

Language files are being checked by an algorithm.
So I will edit the code.

You can be sure that it will be fixed with version 24.07 towards the middle of June.

**Comment by turkaysoft** [comment]
I found the fault and fixed it.
In the next version, the Turkish language will no longer be mandatory.
If additional languages are added later, all languages other than English will not be counted as mandatory.

**Comment by turkaysoft** [comment]
The bug fixed version has been released.
Thank you for your help.

https://github.com/roines45/glow/releases/tag/v24.07

**Comment by LinuxUsersLinuxMint** [comment]
> The bug fixed version has been released. Thank you for your help.
> 
> https://github.com/roines45/glow/releases/tag/v24.07

As a Glow fan, thank you for taking care of the problem and solving it. I am excitedly waiting for 24.08. Every version of Glow is very exciting for me. This is the software I enjoy using the most.
